### ISSUE TITLE
Command line parameters

### ISSUE THREAD

**Issue by piradoiv** [piradoiv/Prack#1]
If you want to start the server listening to another host or port, this is the actual way:

```
./PrackServerApp 0.0.0.0 4242
```

It would be great to add some executable flags instead, so we can launch the server in this way:

```
./PrackServerApp -h 0.0.0.0 -p 4242
```
or
```
./PrackServerApp --host 0.0.0.0 --port 4242
```

Bonus!: Create a `--help` argument with the usage tips.

**Comment by piradoiv** [comment]
I totally agree, the code also defaults the port in one place to 80 and in another one to 8080, I guess it should be 80 by default.

**Comment by piradoiv** [comment]
`TCustomApplication` class (`CustApp` unit) probably has everything we need.

fpcsrc/packages/fcl-base/src/custapp.pp

**Comment by piradoiv** [comment]
https://www.freepascal.org/docs-html/rtl/getopts/getopt.html

**Comment by zamronypj** [comment]
Agree. I think Prack needs capability to set listening host/port individually for gateway server and API server. Either thorough command line parameter or config file (for example JSON). 

Current implementation cannot set API server listening host/port individually without set gateway server listening port too.
