### ISSUE TITLE
It shouldn't be required to use Lazarus to build the project

### ISSUE THREAD

**Issue by piradoiv** [piradoiv/Prack#6]
What about http://wiki.freepascal.org/FPMake?

**Comment by zamronypj** [comment]
In my fork I am not using FPMake, but simple bash script with a bunch of compiler switches.

**Comment by piradoiv** [comment]
That's really interesting, thank you!

**Comment by piradoiv** [comment]
Hey @zamronypj, what about a Makefile?
https://github.com/piradoiv/Prack/pull/14

**Comment by zamronypj** [comment]
Nice.
